export const DefaultLocations = [
  {
    name: 'EHAM',
    x: 4.77,
    y: 52.30,
    availability: []
  }, {
    name: 'EHRD',
    x: 4.42,
    y: 51.95,
    availability: []
  }, {
    name: 'EHTW',
    x: 6.98,
    y: 52.28,
    availability: []
  }, {
    name: 'EHBK',
    x: 5.76,
    y: 50.95,
    availability: []
  }, {
    name: 'EHFS',
    x: 3.68,
    y: 51.46,
    availability: []
  }, {
    name: 'EHDB',
    x: 5.18,
    y: 52.12,
    availability: []
  }, {
    name: 'EHGG',
    x: 6.57,
    y: 53.10,
    availability: []
  }, {
    name: 'EHKD',
    x: 4.74,
    y: 52.93,
    availability: []
  }, {
    name: 'EHAK',
    x: 3.81,
    y: 55.399,
    availability: []
  }, {
    name: 'EHDV',
    x: 2.28,
    y: 53.36,
    availability: []
  }, {
    name: 'EHFZ',
    x: 3.94,
    y: 54.12,
    availability: []
  }, {
    name: 'EHFD',
    x: 4.67,
    y: 54.83,
    availability: []
  }, {
    name: 'EHHW',
    x: 6.04,
    y: 52.037,
    availability: []
  }, {
    name: 'EHKV',
    x: 3.68,
    y: 53.23,
    availability: []
  }, {
    name: 'EHMG',
    x: 4.93,
    y: 53.63,
    availability: []
  }, {
    name: 'EHMA',
    x: 5.94,
    y: 53.54,
    availability: []
  }, {
    name: 'EHQE',
    x: 4.15,
    y: 52.92,
    availability: []
  }, {
    name: 'EHPG',
    x: 3.3416,
    y: 52.36,
    availability: []
  }
];
